"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { FieldGroup } from "@/components/ui/field"
import { useMt } from "@/lib/mt/store"
import { permittedTasks, useTeacherId } from "@/lib/mt/derive"
import { formalTaskName, lessonsOfWeek, weekOfDate } from "@/lib/mt/model"
import { useResearchContext } from "@/lib/research/context"
import { useResearchForm } from "@/lib/research/use-form"
import { canEditGroup, canLeadGroup, canReadActivity, canReadDocument, courseTaskMap, coursesFor, emptyAccess, type Activity } from "@/lib/research/model"
import { Choices, DiscussionThread, Panel, RField, RSelect, RichText, documentHref } from "./primitives"

export function ActivityBoard({ group }: { group: string }) {
  const { state,actor,catalog,people,command } = useResearchContext()
  const mt = useMt(); const teacher = useTeacherId()
  const [error,setError] = useState("")
  const form = useResearchForm(`activity-create:${group}`,{ id: "",title: "",type: "集体备课" as Activity["type"],course: "",taskId: "",start: "",end: "",participants: [] as string[],materials: [] as string[],conclusion: "",week: String(weekOfDate(actor.date)),lesson: "",criterionId: "",samples: "" })
  const editable = canEditGroup(state,actor,group)
  const courses = coursesFor(catalog,group)
  const tasks = permittedTasks(mt.biz,teacher).filter(t => courseTaskMap[form.value.course] === t.course_id)
  const lessons = lessonsOfWeek(mt.biz.variant,Number(form.value.week),tasks.map(t => t.id))
  const lesson = lessons.find(l => l.id === form.value.lesson)
  const docs = state.documents.filter(d => !d.archived && canReadDocument(state,actor,d) && (!form.value.course || d.course === form.value.course))
  const activities = state.activities.filter(a => a.group === group && canReadActivity(state,actor,a))
  function save() {
    const f = form.value; const prev = state.activities.find(a => a.id === f.id)
    const currentLesson = lessonsOfWeek(mt.biz.variant,Number(f.week),tasks.map(t => t.id)).find(l => l.id === f.lesson)
    if (f.type === "示范课" && (!currentLesson || !tasks.some(t => t.id === currentLesson.task_id))) return setError("请关联本人真实课次；课次已调整时请重新核对，不会另造一节课。")
    const activity: Activity = { id: f.id || crypto.randomUUID(),group,title: f.title.trim(),type: f.type,owner: prev?.owner || actor.staff,course: f.course,taskId: f.taskId || null,start: f.type === "示范课" && currentLesson ? `${currentLesson.actual_date}T${currentLesson.period.start}` : f.start,end: f.type === "示范课" && currentLesson ? `${currentLesson.actual_date}T${currentLesson.period.end}` : f.end,participants: [...new Set([actor.staff,...f.participants])],lesson: f.type === "示范课" && currentLesson ? { taskId: currentLesson.task_id,lessonId: currentLesson.id,date: currentLesson.actual_date,period: currentLesson.period.number,label: formalTaskName(tasks.find(t => t.id === currentLesson.task_id)!),room: currentLesson.room } : null,materials: f.materials.map(id => ({ documentId: id,version: docs.find(d => d.id === id)?.version || 0 })),conclusion: f.conclusion,share: prev?.share || emptyAccess(group),responses: prev?.responses || {},attendance: prev?.attendance || {},criterionId: f.criterionId || null,trials: f.samples.split(/\n\s*\n/).filter(x => x.trim()).map((answer,index) => ({ id: prev?.trials[index]?.id || crypto.randomUUID(),answer,notes: "匿名合成试评内容；不产生学生成绩或课堂事实",decisions: prev?.trials[index]?.decisions || {} })),version: prev?.version || 1 }
    const result = command({ type: "save-activity",activity })
    if (!result.ok) setError(result.error); else { form.reset(); setError("") }
  }
  return <div className="flex flex-col gap-5">{editable && <Panel title={form.value.id ? "修订活动安排与结论" : "安排一次教研活动"} description="独立试讲不是课堂事实；真实示范课只关联已有课次。"><FieldGroup className="grid sm:grid-cols-2"><RField label="活动主题" value={form.value.title} onChange={title => form.set({ title })} /><RSelect label="活动类型" value={form.value.type} options={["集体备课","独立试讲","示范课","同课异构","专题研讨","评分校准"].map(value => ({ value,label: value }))} onChange={type => form.set({ type: type as Activity["type"],lesson: "" })} /><RSelect label="活动相关课程" value={form.value.course} options={courses.map(c => ({ value: c.code,label: c.name }))} onChange={course => form.set({ course,lesson: "" })} placeholder="不指定具体课程" /><RSelect label="关联教研任务（可选）" value={form.value.taskId} options={state.tasks.filter(t => t.group === group).map(t => ({ value: t.id,label: t.title }))} onChange={taskId => form.set({ taskId })} placeholder="独立活动" /></FieldGroup>
      {form.value.type === "示范课" ? <><FieldGroup className="grid sm:grid-cols-2"><RField label="已有课表的学校周次" type="number" min={1} value={form.value.week} onChange={week => form.set({ week,lesson: "" })} /><RSelect label="关联本人真实课次" value={form.value.lesson} options={lessons.map(l => ({ value: l.id,label: `${l.actual_date} 第${l.period.number}节 ${formalTaskName(tasks.find(t => t.id === l.task_id)!)} · ${l.room || "教室待确认"}` }))} onChange={id => form.set({ lesson: id })} placeholder="先选课程，再选择已有真实课次" /></FieldGroup><p>时间、教室取该课次，不另建学生出勤、评价或周反馈记录。{lesson && `本次：${lesson.actual_date} ${lesson.period.start}–${lesson.period.end}`}</p><Link href="/timetable/my" className="self-start text-primary underline">需要改时间或教室？进入原课表调整流程</Link></> : <FieldGroup className="grid sm:grid-cols-2"><RField label="活动开始时间" type="datetime-local" value={form.value.start} onChange={start => form.set({ start })} /><RField label="活动结束时间" type="datetime-local" value={form.value.end} onChange={end => form.set({ end })} /></FieldGroup>}
      <Choices label="参与者（可明确邀请跨组教师，不改变科组任命）" value={form.value.participants} options={people.filter(p => p.status !== "left").map(p => ({ value: p.id,label: `${p.name}${p.accountStatus !== "enabled" ? " · 无可用账号，需另行沟通" : ""}` }))} onChange={participants => form.set({ participants })} /><Choices label="关联已有材料的保存版本" value={form.value.materials} options={docs.map(d => ({ value: d.id,label: `${d.title} v${d.version}` }))} onChange={materials => form.set({ materials })} />{form.value.type === "评分校准" && <FieldGroup><RSelect label="本次校准的评分依据" value={form.value.criterionId} options={state.criteria.filter(c => c.group === group).map(c => ({ value: c.id,label: `${c.kind} · ${c.title} v${c.version}` }))} onChange={criterionId => form.set({ criterionId })} placeholder="明确采用哪份依据" /><RField label="少量匿名示例作答（空行分隔）" type="textarea" rows={5} value={form.value.samples} onChange={samples => form.set({ samples })} description="只用于参与者试评与讨论，不新建考试或真实学生分数。" /></FieldGroup>}<FieldGroup><RField label="研讨结论／最终采用说明" type="textarea" value={form.value.conclusion} onChange={conclusion => form.set({ conclusion })} /></FieldGroup><div className="flex gap-2"><Button onClick={save} disabled={!form.value.title.trim()}>保存活动安排与结论</Button>{form.value.id && <Button variant="outline" onClick={() => form.reset()}>取消当前活动修订</Button>}</div>{error && <p role="alert" className="text-destructive">{error}</p>}</Panel>}
    {activities.map(a => <ActivityCard key={a.id} activity={a} onEdit={() => form.set({ id: a.id,title: a.title,type: a.type,course: a.course,taskId: a.taskId || "",start: a.start,end: a.end,participants: a.participants,materials: a.materials.map(m => m.documentId),conclusion: a.conclusion,week: String(weekOfDate(a.lesson?.date || a.start.slice(0,10))),lesson: a.lesson?.lessonId || "",criterionId: a.criterionId || "",samples: a.trials.map(t => t.answer).join("\n\n") })} />)}{!activities.length && <Panel title="暂无可访问活动"><p>可以安排无学生的试讲或研讨；没有实际活动时不生成到场或课堂事实。</p></Panel>}
  </div>
}
function ActivityCard({ activity: a,onEdit }: { activity: Activity; onEdit: () => void }) {
  const { state,actor,people,command } = useResearchContext(); const mt = useMt(); const teacher = useTeacherId()
  const [error,setError] = useState("")
  const trialForm = useResearchForm(`activity-trials:${a.id}`,{ decisions: {} as Record<string,string> })
  const canManage = actor.staff === a.owner || canLeadGroup(state,actor,a.group)
  const legalOwnLesson = a.lesson && permittedTasks(mt.biz,teacher).some(t => t.id === a.lesson!.taskId)
  const current = a.lesson && legalOwnLesson ? lessonsOfWeek(mt.biz.variant,weekOfDate(a.lesson.date),[a.lesson.taskId]).find(l => l.id === a.lesson!.lessonId) : null
  const issue = a.lesson && legalOwnLesson && (!current || `${current.actual_date}T${current.period.start}` !== a.start || current.room !== a.lesson.room)
  const execute = (action: Parameters<typeof command>[0]) => { const result = command(action); setError(result.ok ? "" : result.error) }
  return <Panel title={a.title} description={`${a.type} · ${a.start.replace("T"," ")}—${a.end.replace("T"," ")} · v${a.version}`} action={canManage && canEditGroup(state,actor,a.group) ? <Button variant="outline" onClick={onEdit}>编辑安排／结论</Button> : undefined}>
    {a.lesson ? <p>关联既有课次：{a.lesson.label} · {a.lesson.date} 第{a.lesson.period}节 · {a.lesson.room || "未确定教室"} · {a.lesson.lessonId}。这里只显示公开工作安排，不开放学生名单或记录。</p> : <p className="text-muted-foreground">教研活动，不生成学生出勤、课堂评价、成绩或周反馈事实。</p>}{issue && <p role="alert" className="text-destructive">关联课次已有调整或不可用。活动保留原关联供核对；请在原课表流程处理后明确修订活动，不会自动另造课次。</p>}
    {a.taskId && <p>关联任务：{state.tasks.find(t => t.id === a.taskId)?.title || "来源事项不可用"}</p>}
    {a.participants.map(id => { const p = people.find(x => x.id === id); const online = p?.accountStatus === "enabled" && p.status !== "left"; return <div className="flex flex-wrap items-center justify-between gap-2" key={id}><p>{p?.name || "正式成员"} · {online ? a.responses[id] || "已列入邀请，回应未记录（不声称已读）" : "无可用账号，不发送／显示线上送达、回应"} · 到场 {a.attendance[id] || "未核实"}</p>{canManage && a.start.slice(0,10) <= actor.date && <div className="flex gap-2"><Button variant="outline" onClick={() => execute({ type: "attend-activity",id: a.id,staff: id,status: "到场" })}>核实到场</Button><Button variant="outline" onClick={() => execute({ type: "attend-activity",id: a.id,staff: id,status: "未到场" })}>核实未到场</Button></div>}</div> })}
    {a.participants.includes(actor.staff) && <div className="flex gap-2"><Button variant="outline" onClick={() => execute({ type: "respond-activity",id: a.id,response: "参加" })}>回应参加</Button><Button variant="outline" onClick={() => execute({ type: "respond-activity",id: a.id,response: "无法参加" })}>回应无法参加</Button></div>}
    <h3 className="font-semibold">关联材料与依据</h3>{a.materials.map(ref => { const d = state.documents.find(x => x.id === ref.documentId); return d && canReadDocument(state,actor,d) ? <Link key={ref.documentId} className="text-primary underline" href={documentHref(d,actor.staff,canEditGroup(state,actor,d.owner),ref.version)}>{d.title} v{ref.version}{d.version !== ref.version ? `（来源已更新 v${d.version}，当前采用不变）` : ""}</Link> : <p key={ref.documentId}>材料受限；参加活动不授予材料或来源组工作区权限。</p> })}{!a.materials.length && <p className="text-muted-foreground">没有关联材料。</p>}
    {a.type === "评分校准" && <><p>评分依据：{state.criteria.find(c => c.id === a.criterionId)?.title || "尚未明确"}</p>{a.trials.map(t => <section className="flex flex-col gap-3 rounded-lg border p-4" key={t.id}><RichText text={t.answer} /><p className="text-muted-foreground">{t.notes}</p>{Object.entries(t.decisions).map(([id,decision]) => <p key={id}>{people.find(p => p.id === id)?.name} 的试评：{decision}</p>)}{a.participants.includes(actor.staff) && <><RField label="我的试评与分歧说明" type="textarea" value={trialForm.value.decisions[t.id] ?? t.decisions[actor.staff] ?? ""} onChange={decision => trialForm.set({ decisions: { ...trialForm.value.decisions,[t.id]: decision } })} /><Button variant="outline" className="self-start" onClick={() => execute({ type: "trial-activity",id: a.id,trial: t.id,decision: trialForm.value.decisions[t.id] ?? "" })}>保存本次试评说明</Button></>}</section>)}</>}
    <h3 className="font-semibold">研讨结论／最终采用说明</h3><RichText text={a.conclusion || "尚未形成结论，不假报完成。"} />{error && <p role="alert" className="text-destructive">{error}</p>}{(canEditGroup(state,actor,a.group) || a.participants.includes(actor.staff)) && <DiscussionThread target={`activity:${a.id}`} />}
  </Panel>
}
