"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { FieldGroup } from "@/components/ui/field"
import { SYS_BASIC4 } from "@/lib/mt/schemes"
import { useResearchContext } from "@/lib/research/context"
import { useResearchForm } from "@/lib/research/use-form"
import { canReadDocument, itemReadable, leafItems, type Criterion } from "@/lib/research/model"
import { Panel, RField, RSelect } from "./primitives"

function blankCriterion(group: string, kind: Criterion["kind"] = "课堂表现方案"): Criterion {
  return { id: "", group, kind, title: "", version: 1, source: "", notes: "", recommended: false, dimensions: [], levels: structuredClone(SYS_BASIC4.levels), documentId: null, itemId: null, maxScore: null, scoring: "", testName: "", thresholds: [] }
}

export function CriterionEditor({ group, criterion, onClose }: { group: string; criterion?: Criterion; onClose: () => void }) {
  const { state, actor, command } = useResearchContext()
  const form = useResearchForm(`criterion-editor:${criterion?.id || group}:v${criterion?.version || 1}`, { criterion: criterion ? structuredClone(criterion) : blankCriterion(group), thresholdRows: (criterion?.thresholds ?? []).map((t, index) => ({ id: `threshold-${index}`, minimum: String(t.minimum), code: t.code })) })
  const c = form.value.criterion
  const [error, setError] = useState("")
  const patch = (value: Partial<Criterion>) => form.set({ criterion: { ...c, ...value } })
  const dimensionScheme = c.kind === "课堂表现方案" || c.kind === "作业质量方案"
  const documents = state.documents.filter(d => !d.archived && (d.kind === "资源" || d.kind === "练习组合") && canReadDocument(state, actor, d))
  const document = documents.find(d => d.id === c.documentId)
  const items = document ? leafItems(document).filter(i => itemReadable(state, actor, i, document.owner)) : []
  function save() {
    if (form.value.thresholdRows.some(t => !t.minimum.trim() || !t.code)) return setError("请填写每条明确分数线及等级；没有依据时移除该行，空白不当作 0 分。")
    const updated = { ...c, id: c.id || crypto.randomUUID(), title: c.title.trim(), levels: c.levels.map(l => ({ ...l, code: l.code.normalize("NFKC").trim().toUpperCase(), label: l.label.trim() })), thresholds: form.value.thresholdRows.map(t => ({ minimum: Number(t.minimum), code: t.code })) }
    const result = command({ type: "criterion", criterion: updated })
    if (!result.ok) return setError(result.error)
    form.reset(); setError(""); onClose()
  }
  return <Panel title={criterion ? `修订 ${criterion.title}` : "共建一份明确用途的评价依据"} description="输入自动保留为本人草稿。保存产生新版本；推荐不改变教师选择，不重算已使用或已发布结果。">
    <FieldGroup className="grid sm:grid-cols-2"><RField label="评价依据名称" value={c.title} onChange={title => patch({ title })} /><RSelect label="评价依据用途" disabled={!!criterion} value={c.kind} options={["课堂表现方案", "作业质量方案", "题目评分依据", "单次考核等级换算"].map(value => ({ value, label: value }))} onChange={kind => form.set({ criterion: blankCriterion(group, kind as Criterion["kind"]), thresholdRows: [] })} /><RField label="评价依据来源（学校自定或真实材料）" value={c.source} onChange={source => patch({ source })} /><RField label="适用说明与依据备注" type="textarea" value={c.notes} onChange={notes => patch({ notes })} /></FieldGroup>
    {dimensionScheme && <section className="flex flex-col gap-3"><h3 className="font-semibold">评价维度与含义</h3>{c.dimensions.map(dimension => <div key={dimension.id} className="flex flex-col gap-3 rounded-lg border p-3"><FieldGroup className="grid sm:grid-cols-2"><RField label="评价维度名称" value={dimension.name} onChange={name => patch({ dimensions: c.dimensions.map(d => d.id === dimension.id ? { ...d, name } : d) })} /><RField label="评价维度含义" type="textarea" value={dimension.meaning} onChange={meaning => patch({ dimensions: c.dimensions.map(d => d.id === dimension.id ? { ...d, meaning } : d) })} /></FieldGroup><Button variant="outline" className="self-start" onClick={() => patch({ dimensions: c.dimensions.filter(d => d.id !== dimension.id) })}>删除此维度</Button></div>)}<Button variant="outline" className="self-start" onClick={() => patch({ dimensions: [...c.dimensions, { id: crypto.randomUUID(), name: "", meaning: "" }] })}>添加评价维度</Button></section>}
    {c.kind !== "题目评分依据" && <section className="flex flex-col gap-3"><h3 className="font-semibold">有序等级字典与判断说明</h3><p className="text-muted-foreground">沿用当前字典起点，A＝优秀。选项描述评价，不承载出勤、未交、免做或“未记录”状态；不是 GPA。</p>{c.levels.map((level, index) => <div key={level.id} className="flex flex-col gap-3 rounded-lg border p-3"><FieldGroup className="grid sm:grid-cols-2"><RField label="等级代码" value={level.code} onChange={code => patch({ levels: c.levels.map(l => l.id === level.id ? { ...l, code } : l) })} /><RField label="等级含义" value={level.label} onChange={label => patch({ levels: c.levels.map(l => l.id === level.id ? { ...l, label } : l) })} /><RField label="等级判断说明" type="textarea" value={level.guide} onChange={guide => patch({ levels: c.levels.map(l => l.id === level.id ? { ...l, guide } : l) })} /></FieldGroup><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={index === 0} onClick={() => { const levels = [...c.levels]; [levels[index - 1], levels[index]] = [levels[index], levels[index - 1]]; patch({ levels }) }}>此等级上移</Button><Button variant="outline" disabled={index === c.levels.length - 1} onClick={() => { const levels = [...c.levels]; [levels[index], levels[index + 1]] = [levels[index + 1], levels[index]]; patch({ levels }) }}>此等级下移</Button><Button variant="outline" onClick={() => patch({ levels: c.levels.filter(l => l.id !== level.id) })}>删除此等级</Button></div></div>)}<Button variant="outline" className="self-start" onClick={() => patch({ levels: [...c.levels, { id: crypto.randomUUID(), code: "", label: "", guide: "" }] })}>添加等级选项</Button></section>}
    {c.kind === "题目评分依据" && <FieldGroup className="grid sm:grid-cols-2"><RSelect label="题目来源资料" value={c.documentId || ""} placeholder="选择有权读取的来源资料" options={documents.map(d => ({ value: d.id, label: `${d.title} v${d.version}` }))} onChange={documentId => patch({ documentId: documentId || null, itemId: null, maxScore: null, scoring: "" })} /><RSelect label="具体题目／小题" value={c.itemId || ""} placeholder="按真实题目标识关联，不按同名猜测" options={items.map(i => ({ value: i.id, label: `${i.title} · ${i.question}${i.subquestion}` }))} onChange={itemId => { const item = items.find(i => i.id === itemId); patch({ itemId: itemId || null, maxScore: item?.maxScore ?? null, scoring: item?.scoring || "", source: document ? `${document.title} v${document.version} · ${item?.source || "定位待填写"}` : c.source }) }} /><RField label="该题满分（未知留空，0 分明确填）" type="number" min={0} value={c.maxScore ?? ""} onChange={value => patch({ maxScore: value.trim() === "" ? null : Number(value) })} /><RField label="得分点与评分说明" type="textarea" rows={5} value={c.scoring} onChange={scoring => patch({ scoring })} /></FieldGroup>}
    {c.kind === "单次考核等级换算" && <section className="flex flex-col gap-3"><FieldGroup><RField label="明确适用的单次考核名称" value={c.testName} onChange={testName => patch({ testName })} /></FieldGroup><p className="text-muted-foreground">没有真实分数线时留空，不生成学校示例线。实际使用时再明确绑定某份作业／模考和参与名单，不作为整科永久规则。</p>{form.value.thresholdRows.map(row => <div key={row.id} className="flex flex-col gap-3 rounded-lg border p-3"><FieldGroup className="grid sm:grid-cols-2"><RField label="该等级最低分数" type="number" min={0} value={row.minimum} onChange={minimum => form.set({ thresholdRows: form.value.thresholdRows.map(t => t.id === row.id ? { ...t, minimum } : t) })} /><RSelect label="分数线对应等级" value={row.code} placeholder="关联当前等级字典" options={c.levels.map(l => ({ value: l.code, label: `${l.code} · ${l.label}` }))} onChange={code => form.set({ thresholdRows: form.value.thresholdRows.map(t => t.id === row.id ? { ...t, code } : t) })} /></FieldGroup><Button variant="outline" className="self-start" onClick={() => form.set({ thresholdRows: form.value.thresholdRows.filter(t => t.id !== row.id) })}>移除此分数线</Button></div>)}<Button variant="outline" className="self-start" onClick={() => form.set({ thresholdRows: [...form.value.thresholdRows, { id: crypto.randomUUID(), minimum: "", code: "" }] })}>添加有明确依据的分数线</Button></section>}
    <label className="flex items-center gap-2"><input type="checkbox" checked={c.recommended} onChange={e => patch({ recommended: e.target.checked })} />作为本组推荐依据（不等于教师采用）</label>
    <div className="flex flex-wrap gap-2"><Button onClick={save} disabled={!c.title.trim()}>保存共建依据新版本</Button><Button variant="outline" onClick={onClose}>返回依据列表（保留草稿）</Button></div>{error && <p role="alert" className="text-destructive">{error}</p>}
  </Panel>
}
