"use client"

import { useState } from "react"
import Link from "next/link"
import { Button, buttonVariants } from "@/components/ui/button"
import { FieldGroup } from "@/components/ui/field"
import { useResearchContext } from "@/lib/research/context"
import { useResearchForm } from "@/lib/research/use-form"
import { activeAt, canEditGroup, canLeadGroup, canReadActivity, ownTodos } from "@/lib/research/model"
import { Choices, Panel, RField, RichText } from "./primitives"

export function CurrentWork({ group,onNavigate }: { group: string; onNavigate: (tab: string) => void }) {
  const { state,actor,people,command } = useResearchContext()
  const [error,setError] = useState("")
  const notice = useResearchForm(`notice-create:${group}`,{ title: "",body: "",recipients: [] as string[],requiresAck: false })
  const issue = useResearchForm(`support-create:${group}`,{ title: "",body: "" })
  const member = canEditGroup(state,actor,group)
  const myTasks = ownTodos(state,actor,group)
  const activities = state.activities.filter(a => a.group === group && canReadActivity(state,actor,a)).sort((a,b) => a.start.localeCompare(b.start))
  const appointments = [...new Set(state.appointments.filter(a => a.group === group && activeAt(a.start,a.end,actor.date)).map(a => a.staff))]
  return <div className="flex flex-col gap-5"><div className="grid gap-5 lg:grid-cols-2"><Panel title={member ? "本人需要处理的事项" : "本组承接概况（管理只读）"} description="同一来源事项与分工不重复计入本人待办，也不以活动量或评论量排名。">{(member ? myTasks : state.tasks.filter(t => t.group === group && !t.parent)).map(t => <Button key={t.id} variant="outline" className="justify-between" onClick={() => onNavigate("任务与协作")}><span className="truncate">{t.title}</span><span>{t.status}</span></Button>)}{member && !myTasks.length && <p className="text-muted-foreground">当前没有需要本人提交的事项。协作邀请不会被计为独立提交任务。</p>}<Button variant="outline" className="self-start" onClick={() => onNavigate("课程与内容")}>阅读大纲与准备教学计划</Button></Panel><Panel title="近期教研活动">{activities.slice(0,5).map(a => <Button key={a.id} variant="outline" className="justify-between" onClick={() => onNavigate("任务与协作")}><span className="truncate">{a.title}</span><span>{a.start.slice(0,10)}</span></Button>)}{!activities.length && <p className="text-muted-foreground">尚无活动安排。</p>}<div className="flex flex-wrap gap-2"><Link className={buttonVariants({ variant: "outline" })} href="/teaching">现有日常教学</Link><Link className={buttonVariants({ variant: "outline" })} href="/homework">现有作业管理</Link></div><p className="text-muted-foreground">没有大纲、计划或完成任务也可以手工记录教学、布置作业。</p></Panel></div>
    {member && <Panel title="与我有关的通知" description="普通通知无需回执。确需确认的安排才显示确认操作。">{state.notices.filter(n => n.group === group && (n.recipients.includes(actor.staff) || n.author === actor.staff)).map(n => <article key={n.id} className="flex flex-col gap-3 rounded-lg border p-4"><h3 className="font-semibold">{n.title}</h3><RichText text={n.body} /><p className="text-muted-foreground">接收范围：{n.recipients.map(id => people.find(p => p.id === id)?.name).join("、")} · {n.requiresAck ? "此安排需要明确确认" : "不要求已读或回执"}</p>{n.requiresAck && n.recipients.includes(actor.staff) && <Button variant="outline" className="self-start" disabled={n.acknowledged.includes(actor.staff)} onClick={() => { const result = command({ type: "ack-notice",id: n.id }); setError(result.ok ? "" : result.error) }}>{n.acknowledged.includes(actor.staff) ? "本人已明确确认" : "确认本人已知悉此安排"}</Button>}</article>)}{canLeadGroup(state,actor,group) && <details><summary className="cursor-pointer text-primary">发布明确范围的本组通知</summary><div className="flex flex-col gap-4 pt-4"><FieldGroup><RField label="通知名称" value={notice.value.title} onChange={title => notice.set({ title })} /><RField label="通知正文" type="textarea" value={notice.value.body} onChange={body => notice.set({ body })} /></FieldGroup><Choices label="站内接收成员" value={notice.value.recipients} options={appointments.map(id => ({ value: id,label: `${people.find(p => p.id === id)?.name}${people.find(p => p.id === id)?.accountStatus !== "enabled" ? "（没有可用账号，不发送）" : ""}`,disabled: people.find(p => p.id === id)?.accountStatus !== "enabled" }))} onChange={recipients => notice.set({ recipients })} /><label className="flex items-center gap-2"><input type="checkbox" checked={notice.value.requiresAck} onChange={e => notice.set({ requiresAck: e.target.checked })} />这项安排确需接收人明确确认</label><Button className="self-start" disabled={!notice.value.title.trim() || !notice.value.body.trim() || !notice.value.recipients.length} onClick={() => { const result = command({ type: "notice",notice: { ...notice.value,id: crypto.randomUUID(),group,acknowledged: [],author: actor.staff,at: actor.date } }); if (!result.ok) setError(result.error); else notice.reset() }}>发布本组通知</Button></div></details>}</Panel>}
    <Panel title="需要学校协调的事项" description="只有明确提交的协调问题进入学校统筹，不汇总私人草稿或学生明细。">{state.issues.filter(i => i.group === group).map(i => <article key={i.id} className="rounded-lg border p-4"><h3 className="font-semibold">{i.title} · {i.status}</h3><RichText text={i.body} />{i.response && <RichText text={`学校回复：${i.response}`} />}</article>)}{member && <details><summary className="cursor-pointer text-primary">提交本组协调问题</summary><div className="flex flex-col gap-3 pt-3"><FieldGroup><RField label="需要协调的事项" value={issue.value.title} onChange={title => issue.set({ title })} /><RField label="具体问题（不填写学生或私人信息）" type="textarea" value={issue.value.body} onChange={body => issue.set({ body })} /></FieldGroup><Button className="self-start" disabled={!issue.value.title.trim()} onClick={() => { const result = command({ type: "support",issue: { ...issue.value,id: crypto.randomUUID(),group,response: "",status: "待协调",author: actor.staff } }); if (!result.ok) setError(result.error); else issue.reset() }}>明确提交给学校</Button></div></details>}</Panel>{error && <p role="alert" className="text-destructive">{error}</p>}
  </div>
}
