"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { FieldGroup, FieldSet, FieldLegend } from "@/components/ui/field"
import { useResearchContext } from "@/lib/research/context"
import { emptyAccess, groups, type Access, type Assessment, type AssessmentPath, type Document } from "@/lib/research/model"
import { Choices, RField, RSelect } from "./primitives"

export function DocumentMetadata({ document: doc,patch }: { document: Document; patch: (values: Partial<Document>) => void }) {
  const { catalog,actor,people } = useResearchContext()
  const [error,setError] = useState("")
  const units = catalog.units.filter(u => u.courseCode === doc.course).map(u => ({ value: u.code,label: `${u.short} · ${u.name} (${u.officialCode})` }))
  const personal = !groups.some(g => g.id === doc.owner)
  return <div className="flex flex-col gap-5">
    <FieldGroup className="grid sm:grid-cols-2"><RField label="名称" value={doc.title} onChange={title => patch({ title })} required /><RField label="内容语言" value={doc.language} onChange={language => patch({ language })} /><RField label="适用年份／学年" value={doc.years} onChange={years => patch({ years })} /><RField label="采用的来源版本" value={doc.sourceVersion} onChange={sourceVersion => patch({ sourceVersion })} /><RField label="来源文件／链接及定位" value={doc.source} onChange={source => patch({ source })} description="仅显示 http(s) 链接；上传文件不会被声称已经解析。" /><RSelect label="教学范围" value={doc.scope} onChange={scope => patch({ scope: scope as Document["scope"],unitIds: [] })} options={[{ value: "whole",label: "完整课程" },{ value: "units",label: "目录中的明确单元" }]} /></FieldGroup>
    {doc.scope === "units" && <Choices label="选择本课程的真实单元" options={units} value={doc.unitIds} onChange={unitIds => patch({ unitIds })} />}
    <FieldGroup><RField label="课程目标" type="textarea" value={doc.objectives} onChange={objectives => patch({ objectives })} /><RField label="先修要求" type="textarea" value={doc.prerequisites} onChange={prerequisites => patch({ prerequisites })} /><RField label="整体说明／教学备注" type="textarea" value={doc.notes} onChange={notes => patch({ notes })} /></FieldGroup>
    {(doc.kind === "资源" || doc.kind === "练习组合") && <FieldGroup className="grid sm:grid-cols-2"><RSelect label="资料类型" value={doc.resourceType} onChange={resourceType => patch({ resourceType: resourceType as Document["resourceType"] })} options={["教材","练习册","真题","答案与评分资料","讲义课件","实验材料","教学案例","常见错误材料","练习组合"].map(value => ({ value,label: value }))} /><RField label="版次／版本" value={doc.edition} onChange={edition => patch({ edition })} /><RField label="作者／出版者或维护归属" value={doc.publisher} onChange={publisher => patch({ publisher })} />{doc.resourceType === "真题" && <><RField label="考试年份（可空）" value={doc.examYear} onChange={examYear => patch({ examYear })} /><RField label="场次（可空）" value={doc.session} onChange={session => patch({ session })} /><RField label="试卷代码（可空）" value={doc.paperCode} onChange={paperCode => patch({ paperCode })} /></>}</FieldGroup>}
    <details className="rounded-lg border p-4"><summary className="cursor-pointer font-semibold">来源附件与共享范围</summary><div className="flex flex-col gap-4 pt-4"><RSelect label="资料共享范围" value={doc.share.audience} onChange={audience => patch({ share: { ...doc.share,audience: audience as Access["audience"] } })} options={[...(personal ? [{ value: "owner",label: "仅本人" }] : [{ value: "group",label: "本组内部" }]),{ value: "school",label: "本校教职工（不转移归属）" },{ value: "specified",label: "明确科组／教师" }]} />{doc.share.audience === "specified" && <><Choices label="明确共享给哪些科组" options={groups.map(g => ({ value: g.id,label: g.name }))} value={doc.share.groups} onChange={selected => patch({ share: { ...doc.share,groups: selected } })} /><Choices label="明确共享给哪些教师" options={people.filter(p => p.accountStatus === "enabled" && p.status !== "left").map(p => ({ value: p.id,label: p.name }))} value={doc.share.staff} onChange={staff => patch({ share: { ...doc.share,staff } })} /></>}
      <p className="text-muted-foreground">共享不转移作者或归属，不扩大其中的来源、答案及附件授权。受限答案和未公开试卷不能通过复制解除限制。</p>
      <label className="flex flex-col gap-2">关联来源文件（PDF、图片或文本，单个不超过 2 MB）<input className="text-sm" type="file" accept="application/pdf,image/png,image/jpeg,image/webp,text/plain" onChange={async e => { const file = e.target.files?.[0]; e.target.value = ""; if (!file) return; if (file.size > 2*1024*1024 || !["application/pdf","image/png","image/jpeg","image/webp","text/plain"].includes(file.type)) return setError("文件格式不支持或超过 2 MB；没有上传／解析服务，不假报成功。"); try { const data = await new Promise<string>((resolve,reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file) }); patch({ files: [...doc.files,{ id: crypto.randomUUID(),name: file.name,type: file.type,data,access: personal ? emptyAccess(actor.staff) : { audience: "group",groups: [],staff: [] } }] }); setError("") } catch { setError("文件读取失败，未添加附件。") } }} /></label>
      {doc.files.map(file => <div key={file.id} className="flex flex-wrap items-center justify-between gap-2"><span>{file.name} · {file.access.audience === "owner" ? "仅本人" : "独立授权"}</span><Button variant="outline" onClick={() => patch({ files: doc.files.filter(f => f.id !== file.id) })}>移除附件关联</Button></div>)}<p className="text-muted-foreground">只关联文件，不执行 OCR 或大纲解析；已整理内容需要手工录入。附件仍需保存内容草稿。</p>{error && <p role="alert" className="text-destructive">{error}</p>}</div></details>
    {doc.kind === "大纲" && <AssessmentEditor document={doc} patch={patch} />}
  </div>
}
function AssessmentEditor({ document: doc,patch }: { document: Document; patch: (values: Partial<Document>) => void }) {
  const { catalog } = useResearchContext()
  const update = (id: string,values: Partial<Assessment>) => patch({ assessments: doc.assessments.map(a => a.id === id ? { ...a,...values } : a) })
  const pathUpdate = (id: string,values: Partial<AssessmentPath>) => patch({ paths: doc.paths.map(p => p.id === id ? { ...p,...values } : p) })
  const options = doc.assessments.map(a => ({ value: a.id,label: a.title }))
  return <FieldSet><FieldLegend>大纲规定的考核结构（不是单次测试等级）</FieldLegend><p className="text-sm text-muted-foreground">只填写来源明确提供的项目、组合及权重；考核项目与目录单元是不同对象。未知权重保留为空。</p><div className="flex flex-col gap-4">{doc.assessments.map(a => <section className="flex flex-col gap-4 rounded-lg border p-4" key={a.id}><FieldGroup className="grid sm:grid-cols-2"><RField label="考核项目名称" value={a.title} onChange={title => update(a.id,{ title })} /><RField label="项目来源定位" value={a.source} onChange={source => update(a.id,{ source })} /><RField label="先修／条件限制" value={a.conditions} onChange={conditions => update(a.id,{ conditions })} /><RField label="评分量规（源材料提供时）" type="textarea" value={a.rubric} onChange={rubric => update(a.id,{ rubric })} /></FieldGroup><Choices label="覆盖的学习要求" options={doc.items.map(i => ({ value: i.id,label: i.title }))} value={a.itemIds} onChange={itemIds => update(a.id,{ itemIds })} /><Choices label="与哪些真实单元相关" options={catalog.units.filter(u => u.courseCode === doc.course).map(u => ({ value: u.code,label: `${u.short} · ${u.name}` }))} value={a.unitIds} onChange={unitIds => update(a.id,{ unitIds })} /><Button variant="outline" className="self-start" onClick={() => patch({ assessments: doc.assessments.filter(x => x.id !== a.id),paths: doc.paths.map(p => ({ ...p,required: p.required.filter(id => id !== a.id),optional: p.optional.filter(id => id !== a.id) })) })}>移除此考核项目</Button></section>)}<Button variant="outline" className="self-start" onClick={() => patch({ assessments: [...doc.assessments,{ id: crypto.randomUUID(),title: "新考核项目",unitIds: [],itemIds: [],conditions: "",source: "",rubric: "" }] })}>添加有依据的考核项目</Button>
      {doc.paths.map(p => <section key={p.id} className="flex flex-col gap-4 rounded-lg border p-4"><FieldGroup className="grid sm:grid-cols-2"><RField label="组合适用资格／目标" value={p.target} onChange={target => pathUpdate(p.id,{ target })} /><RField label="组合来源" value={p.source} onChange={source => pathUpdate(p.id,{ source })} /><RField label="选考数量（未知留空）" type="number" min={0} value={p.choose ?? ""} onChange={value => pathUpdate(p.id,{ choose: value === "" ? null : Number(value) })} /><RField label="组合条件" value={p.conditions} onChange={conditions => pathUpdate(p.id,{ conditions })} /></FieldGroup><Choices label="必选项目" value={p.required} options={options.filter(o => !p.optional.includes(o.value))} onChange={required => pathUpdate(p.id,{ required })} /><Choices label="选考项目" value={p.optional} options={options.filter(o => !p.required.includes(o.value))} onChange={optional => pathUpdate(p.id,{ optional })} /><FieldGroup className="grid sm:grid-cols-2">{[...p.required,...p.optional].map(id => <RField key={id} label={`${doc.assessments.find(a => a.id === id)?.title} 权重 %（未知留空）`} type="number" value={p.weights[id] ?? ""} onChange={value => pathUpdate(p.id,{ weights: { ...p.weights,[id]: value === "" ? null : Number(value) } })} />)}</FieldGroup><Button variant="outline" className="self-start" onClick={() => patch({ paths: doc.paths.filter(x => x.id !== p.id) })}>移除此组合</Button></section>)}<Button variant="outline" className="self-start" onClick={() => patch({ paths: [...doc.paths,{ id: crypto.randomUUID(),target: "",required: [],optional: [],choose: null,weights: {},conditions: "",source: "" }] })}>添加有依据的考核组合</Button></div></FieldSet>
}
