"use client"

import { useState } from "react"
import { totals, type Document, type Item } from "@/lib/research/store"

const input = "w-full rounded-lg border bg-background px-3 py-2 text-sm"
const button = "rounded-lg border bg-background px-3 py-2 text-sm hover:bg-muted disabled:opacity-40"
export function DocumentEditor({ document: doc, editable, update, copy, toPlan }: { document: Document; editable: boolean; update: (doc: Document) => void; copy: () => void; toPlan: (items: Item[]) => void }) {
  const [query, setQuery] = useState("")
  const [selected, setSelected] = useState<string[]>([])
  const [allocation, setAllocation] = useState<number | null>(null)
  const t = totals(doc)
  const patch = (values: Partial<Document>) => update({ ...doc, ...values, version: doc.version + 1 })
  const itemPatch = (id: string, values: Partial<Item>) => patch({ items: doc.items.map(i => i.id === id ? { ...i, ...values } : i) })
  const eligible = doc.items.filter(i => selected.includes(i.id) && !i.fixed)
  function split(item: Item) {
    const index = doc.items.findIndex(i => i.id === item.id)
    const first = item.minutes === null ? null : Math.floor(item.minutes / 2)
    const children = [{ ...item, id: crypto.randomUUID(), title: `${item.title} · 第一部分`, minutes: first }, { ...item, id: crypto.randomUUID(), title: `${item.title} · 第二部分`, minutes: item.minutes === null ? null : item.minutes - first!, week: "" }]
    patch({ items: [...doc.items.slice(0, index), ...children, ...doc.items.slice(index + 1)] })
  }
  return <section className="flex flex-col gap-5 rounded-xl border bg-card p-5 text-card-foreground">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">{doc.kind} · 修订 {doc.version} · {editable ? "修改即时保存到本机" : "只读"}</p><h2 className="text-xl font-semibold">{doc.title}</h2></div><button className={button} onClick={copy}>复制为个人版本</button></header>
    <p className="text-sm text-muted-foreground">来源：{doc.source || "未提供来源"}。历史引用保留当时内容，不随此处修订自动替换。</p>
    <fieldset disabled={!editable} className="grid gap-4 sm:grid-cols-2"><label className="text-sm">名称<input className={input} value={doc.title} onChange={e => patch({ title: e.target.value })} /></label><label className="text-sm">来源文件定位／链接<input className={input} value={doc.source} onChange={e => patch({ source: e.target.value })} /></label><label className="text-sm sm:col-span-2">说明、先修要求及考核依据<textarea className={input} value={doc.notes} onChange={e => patch({ notes: e.target.value })} rows={3} /></label></fieldset>
    {doc.kind === "计划" && <div className="flex flex-col gap-3 rounded-lg bg-muted p-4"><fieldset disabled={!editable} className="grid gap-3 sm:grid-cols-3">{([['总预算（分钟，可空）', 'budget'], ['机动（分钟）', 'reserve'], ['每课时分钟（请确认学校设置）', 'period']] as const).map(([label, key]) => <label key={key} className="text-sm">{label}<input className={input} type="number" min={key === 'period' ? 1 : 0} value={doc[key] ?? ''} onChange={e => patch({ [key]: e.target.value === '' ? key === 'reserve' ? 0 : null : Math.max(key === 'period' ? 1 : 0, Number(e.target.value)) })} /></label>)}</fieldset><p className="text-sm">已分配 {t.allocated} 分钟 · 机动 {doc.reserve} 分钟 · {t.remainder === null ? "预算未设置" : t.remainder < 0 ? `超额 ${-t.remainder} 分钟` : `未分配 ${t.remainder} 分钟`}{doc.period ? ` · 已分配折合 ${(t.allocated / doc.period).toFixed(2)} 课时` : ""}</p><p className="text-sm text-muted-foreground">更改每课时分钟只改变换算，不改变实际教学分钟。未分配与 0 分钟分别保留。</p><button disabled={!editable || !eligible.length || t.remainder === null || t.remainder <= 0} className={button} onClick={() => setAllocation(Math.floor((t.remainder ?? 0) / eligible.length))}>预览：均分余额到所选非固定项目</button>{allocation !== null && <div className="flex flex-wrap items-center gap-3 text-sm"><span>为当前所选 {eligible.length} 项各追加 {allocation} 分钟；不动固定项和机动时间，余数保留。</span><button disabled={!eligible.length || allocation * eligible.length > (t.remainder ?? 0)} className={button} onClick={() => { patch({ items: doc.items.map(i => eligible.some(e => e.id === i.id) ? { ...i, minutes: (i.minutes ?? 0) + allocation } : i) }); setAllocation(null) }}>确认分配</button><button className={button} onClick={() => setAllocation(null)}>取消</button></div>}</div>}
    <div className="flex flex-wrap gap-2"><input aria-label="检索正文" placeholder="检索标题、正文、Notes" className={`${input} sm:max-w-xs`} value={query} onChange={e => setQuery(e.target.value)} /><button className={button} disabled={!selected.length} onClick={() => toPlan(doc.items.filter(i => selected.includes(i.id)))}>选中内容建立个人计划</button></div>
    {doc.items.filter(i => `${i.title} ${i.body}`.includes(query)).map(item => <article key={item.id} className="flex flex-col gap-3 rounded-lg border p-4"><div className="flex items-center gap-3"><input aria-label={`选择${item.title}`} type="checkbox" checked={selected.includes(item.id)} onChange={e => setSelected(e.target.checked ? [...selected, item.id] : selected.filter(id => id !== item.id))} /><input aria-label="内容标题" disabled={!editable} className={input} value={item.title} onChange={e => itemPatch(item.id, { title: e.target.value })} /></div><p className="text-sm text-muted-foreground">{item.source || "未提供来源；不视为官方要求"}</p><textarea aria-label="完整内容与Notes" disabled={!editable} className={`${input} leading-relaxed`} rows={6} value={item.body} onChange={e => itemPatch(item.id, { body: e.target.value })} /><fieldset disabled={!editable} className="flex flex-wrap gap-3"><label className="text-sm">所属分组<input className={input} value={item.section} onChange={e => itemPatch(item.id, { section: e.target.value })} /></label>{doc.kind === "计划" && <><label className="text-sm">实际分钟<input className={input} type="number" min={0} value={item.minutes ?? ""} placeholder="未分配" onChange={e => itemPatch(item.id, { minutes: e.target.value === "" ? null : Math.max(0, Number(e.target.value)) })} /></label><label className="text-sm">相对周次备注<input className={input} value={item.week} placeholder="未安排" onChange={e => itemPatch(item.id, { week: e.target.value })} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={item.fixed} onChange={e => itemPatch(item.id, { fixed: e.target.checked })} />固定时长</label></>}</fieldset>{editable && <div className="flex flex-wrap gap-2"><button className={button} disabled={doc.items[0].id === item.id} onClick={() => { const items = [...doc.items]; const index = items.findIndex(i => i.id === item.id); [items[index - 1], items[index]] = [items[index], items[index - 1]]; patch({ items }) }}>上移</button><button className={button} onClick={() => { if (confirm("拆分会用两个子项替代父项，总时长不变；原周次备注保留于第一项，第二项需重新安排。继续？")) split(item) }}>拆分项目</button><button className={button} onClick={() => { if (confirm("删除此项目？已有成果快照不会改变。")) patch({ items: doc.items.filter(i => i.id !== item.id) }) }}>删除</button></div>}</article>)}
    {editable && <button className={button} onClick={() => patch({ items: [...doc.items, { id: crypto.randomUUID(), title: "新教学项目", body: "", source: "教师补充（非官方原文）", minutes: null, fixed: false, week: "", section: "" }] })}>添加内容项目</button>}
  </section>
}
