"use client"

import { Button } from "@/components/ui/button"
import { FieldGroup } from "@/components/ui/field"
import { useResearchContext } from "@/lib/research/context"
import { descendants, emptyItem, itemReadable, moveItem, reorderItem, splitItem, type Document, type Item } from "@/lib/research/model"
import { Choices, RField, RSelect, SourceLinks } from "./primitives"

export function ItemEditor({ document: doc,patch,selected,onSelect,onError }: { document: Document; patch: (values: Partial<Document>) => void; selected: string[]; onSelect: (id: string,checked: boolean) => void; onError: (error: string) => void }) {
  const { catalog,state,actor } = useResearchContext()
  const update = (id: string,values: Partial<Item>) => patch({ items: doc.items.map(i => i.id === id ? { ...i,...values } : i) })
  const changeStructure = (fn: () => Document) => { try { patch({ items: fn().items }); onError("") } catch(e) { onError(e instanceof Error ? e.message : "结构调整失败。") } }
  return <div className="flex flex-col gap-5"><h3 className="font-semibold">内容层级与教学项目</h3><p className="text-sm text-muted-foreground">正文、原文、Notes、译注和教学补充分开保留。修改计划不会反向改写来源大纲。拆分保留来源与跨周分钟，父项转为汇总，避免重复计时。</p>
    {doc.items.map(item => {
      const parent = doc.items.some(i => i.parentId === item.id)
      const excluded = new Set(descendants(doc.items,item.id))
      const readable = itemReadable(state,actor,item,doc.owner)
      return <article key={item.id} className="flex flex-col gap-4 rounded-lg border border-border p-4"><header className="flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(item.id)} onChange={e => onSelect(item.id,e.target.checked)} />{item.title}{parent ? " · 汇总章节" : " · 内容项目"}</label><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => changeStructure(() => reorderItem(doc,item.id,-1))}>上移</Button><Button variant="outline" onClick={() => changeStructure(() => reorderItem(doc,item.id,1))}>下移</Button><Button variant="outline" disabled={parent || !readable} onClick={() => changeStructure(() => splitItem(doc,item.id,[crypto.randomUUID(),crypto.randomUUID()]))}>拆分为两部分</Button><Button variant="outline" onClick={() => { const ids = descendants(doc.items,item.id); if (confirm(`删除“${item.title}”及 ${ids.length-1} 个子项目？相应时长和周分配会一并移除，来源本身不变。`)) patch({ items: doc.items.filter(i => !ids.includes(i.id)) }) }}>删除项目</Button></div></header>
        {!readable ? <p className="text-muted-foreground">来源访问已结束，不能阅读或修订其正文；可以移除受限引用，但不能把它改成公开文字。</p> : <><FieldGroup className="grid sm:grid-cols-2"><RField label="项目标题" value={item.title} onChange={title => update(item.id,{ title })} /><RSelect label="所属章节／分组" value={item.parentId ?? ""} placeholder="顶层内容" options={doc.items.filter(i => !excluded.has(i.id) && i.minutes === null && i.weeks.length === 0).map(i => ({ value: i.id,label: i.title }))} onChange={parentId => changeStructure(() => moveItem(doc,item.id,parentId || null))} /><RSelect label="要求来源类型" value={item.origin} onChange={origin => update(item.id,{ origin: origin as Item["origin"] })} options={["官方原文","学校自编","教师译注","教学补充"].map(value => ({ value,label: value }))} /><RField label="原章节／页码或来源定位" value={item.source} onChange={source => update(item.id,{ source })} /></FieldGroup><FieldGroup><RField label="要求正文／教学内容" type="textarea" rows={4} value={item.body} onChange={body => update(item.id,{ body })} description="公式使用双美元符号包围 LaTeX，阅读模式会实际渲染。" /><RField label="Notes／原要求说明" type="textarea" value={item.notes} onChange={notes => update(item.id,{ notes })} /><RField label="保留的原文" type="textarea" value={item.original} onChange={original => update(item.id,{ original })} /><RField label="教师译注（不标为官方原文）" type="textarea" value={item.translation} onChange={translation => update(item.id,{ translation })} /><RField label="教学补充（原要求不被替换）" type="textarea" value={item.supplement} onChange={supplement => update(item.id,{ supplement })} /></FieldGroup><Choices label="项目对应的真实课程单元（可空）" value={item.unitIds} options={catalog.units.filter(u => u.courseCode === doc.course).map(u => ({ value: u.code,label: `${u.short} · ${u.name}` }))} onChange={unitIds => update(item.id,{ unitIds })} /><SourceLinks references={item.references} owner={doc.owner} />
        {doc.kind === "计划" && <div className="flex flex-col gap-3 rounded-lg bg-muted p-4 text-foreground">{parent ? <p>汇总章节：课时与周安排只计末级子项目，此项不单独计时。</p> : <><FieldGroup className="grid sm:grid-cols-2"><RField label="项目实际分钟（未分配留空）" type="number" min={0} value={item.minutes ?? ""} onChange={value => update(item.id,{ minutes: value === "" ? null : Number(value) })} /><RField label="教学分组备注（可选）" value={item.section} onChange={section => update(item.id,{ section })} /></FieldGroup><label className="flex items-center gap-2"><input type="checkbox" checked={item.fixed} onChange={e => update(item.id,{ fixed: e.target.checked })} />固定时长，不被辅助分配改写</label><p>{item.weeks.length ? `已安排到周 ${item.weeks.reduce((n,w) => n+w.minutes,0)} 分钟；尚未映射 ${item.minutes === null ? "未分配" : item.minutes-item.weeks.reduce((n,w) => n+w.minutes,0)} 分钟` : "未安排相对周次；不会自动塞入某周。"}</p>{item.weeks.map((week,index) => <div key={index} className="flex flex-wrap items-end gap-3"><FieldGroup className="grid flex-1 sm:grid-cols-2"><RField label={`相对周次 ${index+1}`} type="number" min={1} value={week.week} onChange={value => update(item.id,{ weeks: item.weeks.map((w,j) => j === index ? { ...w,week: Number(value) } : w) })} /><RField label={`第 ${week.week} 周分钟`} type="number" min={0} value={week.minutes} onChange={value => update(item.id,{ weeks: item.weeks.map((w,j) => j === index ? { ...w,minutes: Number(value) } : w) })} /></FieldGroup><Button variant="outline" onClick={() => update(item.id,{ weeks: item.weeks.filter((_,j) => j !== index) })}>移除本周安排</Button></div>)}<Button variant="outline" className="self-start" disabled={item.minutes === null} onClick={() => update(item.id,{ weeks: [...item.weeks,{ week: Math.max(0,...item.weeks.map(w => w.week))+1,minutes: 0 }] })}>添加明确的相对周次</Button>{item.minutes !== null && item.weeks.reduce((n,w) => n+w.minutes,0) > item.minutes && <p role="alert" className="text-destructive">周分配超过项目实际分钟；保存前必须调整，不会偷偷重算或截断。</p>}</>}</div>}
        {(doc.kind === "资源" || doc.kind === "练习组合") && <FieldGroup className="grid sm:grid-cols-2"><RField label="印刷页码" value={item.printedPage} onChange={printedPage => update(item.id,{ printedPage })} /><RField label="文件页码" value={item.filePage} onChange={filePage => update(item.id,{ filePage })} /><RField label="题号" value={item.question} onChange={question => update(item.id,{ question })} /><RField label="小题" value={item.subquestion} onChange={subquestion => update(item.id,{ subquestion })} /><RField label="必要共同题干／上下文" type="textarea" value={item.stem} onChange={stem => update(item.id,{ stem })} /><RField label="满分（未知留空，0 单独保存）" type="number" min={0} value={item.maxScore ?? ""} onChange={value => update(item.id,{ maxScore: value === "" ? null : Number(value) })} /><RField label="得分点／评分说明" type="textarea" value={item.scoring} onChange={scoring => update(item.id,{ scoring })} /><RSelect label="关联有权访问的答案资料" value={item.answer?.documentId ?? ""} placeholder="不关联答案" options={state.documents.filter(d => d.kind === "资源" && d.resourceType === "答案与评分资料" && (d.owner === actor.staff || d.share.staff.includes(actor.staff) || d.share.audience === "school")).map(d => ({ value: d.id,label: d.title }))} onChange={documentId => update(item.id,{ answer: documentId ? { documentId,itemId: state.documents.find(d => d.id === documentId)?.items[0]?.id || "" } : null })} />{item.answer && <RSelect label="答案对应条目" value={item.answer.itemId} placeholder="选择答案条目" options={(state.documents.find(d => d.id === item.answer!.documentId)?.items ?? []).map(i => ({ value: i.id,label: i.title }))} onChange={itemId => update(item.id,{ answer: { documentId: item.answer!.documentId,itemId } })} />}</FieldGroup>}
      </>}</article>
    })}
    <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => patch({ items: [...doc.items,emptyItem(crypto.randomUUID())] })}>添加内容项目</Button><Button variant="outline" onClick={() => patch({ items: [...doc.items,{ ...emptyItem(crypto.randomUUID()),title: "新章节／分组" }] })}>添加独立章节／分组</Button></div>
  </div>
}
