'use client'
import { useState } from 'react'
import { useMt } from '@/lib/mt/store'
import { SYSTEM_TEMPLATES, reporting, validTemplate, classicTemplate, type ReportKind, type ReportTemplate, type FrozenReport } from '@/lib/mt/reports'
import { Btn, inputCls } from './ui'
import { ReportView } from './report-view'
import { ReportOptionsEditor } from './report-options-editor'

const descriptions:Record<string,string>={C01:'左侧矩阵，右侧教学与学情说明。',C02:'完整宽表在上，教学与学情说明在下。',C03:'高密度矩阵，适合人数与事件较多的周次。',P01:'课堂、作业与跟进说明集中呈现。',P02:'完整课堂与课次明细，适合具体问题核对。',P03:'数据表与沟通建议相结合，保留完整周记录。'}
export function ReportTemplates({teacherId,buildSamples,onApply}:{teacherId:string;buildSamples:(t:ReportTemplate)=>FrozenReport[];onApply:(t:ReportTemplate)=>void}) {
  const mt=useMt(),state=reporting(mt.biz)
  const [kind,setKind]=useState<ReportKind>('class'),[view,setView]=useState<ReportTemplate|null>(null),[edit,setEdit]=useState<ReportTemplate|null>(null),[object,setObject]=useState(0),[msg,setMsg]=useState('')
  const templates=[...SYSTEM_TEMPLATES,...state.templates.filter(t=>t.owner===teacherId&&!t.archived)].filter(t=>t.kind===kind).map(classicTemplate)
  const active=edit??view,samples=active&&validTemplate(active)?buildSamples(active):[],index=Math.min(object,Math.max(0,samples.length-1))
  const choose=(t:ReportTemplate)=>{setEdit(null);setView(t);setObject(0)}
  const copy=(t:ReportTemplate)=>{setView(null);setEdit({...structuredClone(t),id:crypto.randomUUID(),owner:teacherId,name:`${t.name} · 我的模板`,options:{...t.options,classic:true}});setObject(0)}
  const save=()=>{if(!edit||!edit.name.trim()||!validTemplate(edit)){setMsg('请检查名称与颜色对比度。');return}const result=mt.command('保存经典报告模板',b=>({...b,reporting:{...reporting(b),templates:[...reporting(b).templates.filter(t=>t.id!==edit.id),structuredClone(edit)]}}));setMsg(result.ok?'模板已保存，可跨班级与周次复用。':result.error);if(result.ok){setView(edit);setEdit(null)}}
  return <div className="flex flex-col gap-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">模板中心</h2><p className="text-sm text-muted-foreground">先选结构，再查看一份实际报告。</p></div><label className="text-sm">模板类型 <select aria-label="模板类型" className={inputCls} value={kind} onChange={e=>{setKind(e.target.value as ReportKind);setView(null);setEdit(null);setObject(0)}}><option value="class">班级模板</option><option value="personal">个人模板</option></select></label></div>
    <div className={active?'grid items-start gap-5 lg:grid-cols-[300px_minmax(0,1fr)]':'flex flex-col gap-3'}>
      <div className="flex flex-col gap-3">{templates.map(t=><section key={t.id} className="flex flex-col gap-2 rounded-lg border border-border bg-card p-4 text-card-foreground"><div className="flex items-center justify-between gap-2"><h3 className="font-semibold">{t.name}</h3><span className="text-sm text-muted-foreground">{t.owner?'自定义':t.id}</span></div><p className="text-sm text-muted-foreground">{descriptions[t.preset??t.id]??'可复用的经典报告样式。'}</p><div className="flex flex-wrap gap-2"><Btn size="sm" onClick={()=>choose(t)}>预览</Btn><Btn size="sm" onClick={()=>onApply(t)}>设为当前</Btn><Btn size="sm" onClick={()=>copy(t)}>复制</Btn>{t.owner===teacherId?<><Btn size="sm" onClick={()=>{setView(null);setEdit(structuredClone(t))}}>编辑</Btn><Btn size="sm" onClick={()=>{const result=mt.command('归档经典模板',b=>({...b,reporting:{...reporting(b),templates:reporting(b).templates.map(x=>x.id===t.id?{...x,archived:true}:x)}}));setMsg(result.ok?'已归档，历史报告不变。':result.error);if(result.ok&&active?.id===t.id){setView(null);setEdit(null)}}}>归档</Btn></>:null}</div></section>)}</div>
      {active?<section className="flex min-w-0 flex-col gap-4 rounded-lg border border-border bg-card p-4 text-card-foreground"><div className="flex items-center justify-between gap-2"><h3 className="font-semibold">{active.name}</h3><Btn size="sm" onClick={()=>{setView(null);setEdit(null)}}>关闭预览</Btn></div>{edit?<details open><summary className="cursor-pointer font-semibold">编辑模板参数</summary><div className="mt-3 flex flex-col gap-4"><label className="text-sm">模板名称<input className={inputCls} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><ReportOptionsEditor value={edit} onChange={setEdit}/><div className="flex gap-2"><Btn variant="primary" onClick={save}>保存模板</Btn><Btn onClick={()=>copy(edit)}>另存为</Btn></div></div></details>:<details><summary className="cursor-pointer text-sm">查看参数</summary><p className="text-sm">{active.options?.notesPosition==='right'?'右侧说明':'下方说明'} · {active.options?.density==='compact'?'紧凑':'标准'} · {active.options?.homeworkAppendix?'附加作业明细':'单张主报告'}</p><Btn size="sm" onClick={()=>copy(active)}>复制后调整</Btn></details>}
      {samples.length?<><div className="flex flex-wrap items-center gap-2"><Btn size="sm" disabled={index===0} onClick={()=>setObject(index-1)}>上一个对象</Btn><select aria-label="模板预览对象" className="min-w-0 flex-1 rounded border border-input p-2 text-sm" value={index} onChange={e=>setObject(Number(e.target.value))}>{samples.map((r,i)=><option key={r.key} value={i}>{r.name} · {r.kind==='personal'?'个人':r.audience==='internal'?'校内核对':'班级家长版'}</option>)}</select><Btn size="sm" disabled={index===samples.length-1} onClick={()=>setObject(index+1)}>下一个对象</Btn></div><ReportView report={samples[index]}/></>:<p role="status" className="min-h-64 text-sm">请修正模板配置，或切换有记录的教学周。</p>}</section>:null}
    </div>{msg?<p role="status" className="text-sm">{msg}</p>:null}
  </div>
}
