'use client'
import { useEffect, useState } from 'react'
import { useMt } from '@/lib/mt/store'
import { SYSTEM_TEMPLATES, reporting, validTemplate, templateContrastWarnings, classicTemplate, type ReportKind, type ReportTemplate, type FrozenReport } from '@/lib/mt/reports'
import { SYSTEM_THEMES, applyTheme, themeOf, type ReportTheme } from '@/lib/mt/report-themes'
import { Btn, inputCls } from './ui'
import { ReportView } from './report-view'
import { ReportOptionsEditor } from './report-options-editor'
import { ReportThemeEditor } from './report-theme-editor'

const descriptions:Record<string,string>={C01:'矩阵在左 · 说明在右',C02:'矩阵在上 · 说明在下',C03:'高密度 · 紧凑矩阵',C11:'三卡片 · 总评速览',C12:'仪表盘 · 数据一览',C13:'时间轴 · 一周历程',C14:'快问快答 · 要点速读',C15:'一图流 · 长图分享',C16:'报纸风 · 头条速递',P01:'课堂与作业 · 标准跟进',P02:'完整课次 · 表格详报',P03:'数据与建议 · 家长沟通',P11:'成长档案 · 个人轨迹',P12:'每周一信 · 娓娓道来'}
export function ReportTemplates({teacherId,buildSamples,onApply}:{teacherId:string;buildSamples:(t:ReportTemplate)=>FrozenReport[];onApply:(t:ReportTemplate)=>void}) {
  const mt=useMt(),state=reporting(mt.biz)
  const [kind,setKind]=useState<ReportKind>('class'),[view,setView]=useState<ReportTemplate|null>(null),[edit,setEdit]=useState<ReportTemplate|null>(null),[object,setObject]=useState(0),[msg,setMsg]=useState('')
  const [tab,setTab]=useState<'style'|'theme'>('style'),[theme,setTheme]=useState<ReportTheme>(SYSTEM_THEMES[0]),[themeEdit,setThemeEdit]=useState<ReportTheme|null>(null)
  const templates=[...SYSTEM_TEMPLATES,...state.templates.filter(t=>t.owner===teacherId&&!t.archived)].filter(t=>t.kind===kind).map(classicTemplate)
  const themes=[...SYSTEM_THEMES,...(state.themes??[]).filter(t=>t.owner===teacherId)]
  const layout=edit??view,active=layout?applyTheme(layout,themeEdit??theme):null
  const [previewTemplate,setPreviewTemplate]=useState<ReportTemplate|null>(null)
  const previewKey=active&&validTemplate(active)?JSON.stringify(active):null
  useEffect(()=>{if(!previewKey)return;const timer=setTimeout(()=>setPreviewTemplate(JSON.parse(previewKey)),250);return()=>clearTimeout(timer)},[previewKey])
  const samples=active&&previewTemplate?buildSamples(previewTemplate):[],index=Math.min(object,Math.max(0,samples.length-1))
  const defaultId=state.defaults[teacherId]?.[kind]??(kind==='class'?'C01':'P01')
  const setDefault=()=>{if(!layout||edit)return;const result=mt.command('设置默认报告样式',b=>({...b,reporting:{...reporting(b),defaults:{...reporting(b).defaults,[teacherId]:{...reporting(b).defaults[teacherId],[kind]:layout.id}}}}));setMsg(result.ok?'已设置默认样式，将用于新的发布准备；已有准备不变。':result.error)}
  const choose=(t:ReportTemplate)=>{setEdit(null);setView(t);setObject(0)}
  const copy=(t:ReportTemplate)=>{setView(null);setEdit({...structuredClone(t),id:crypto.randomUUID(),owner:teacherId,name:`${t.name} · 我的样式`});setObject(0)}
  const save=()=>{if(!edit||!edit.name.trim()||!validTemplate(edit)){setMsg('请检查样式名称与配置。');return}const result=mt.command('保存报告样式',b=>({...b,reporting:{...reporting(b),templates:[...reporting(b).templates.filter(t=>t.id!==edit.id),structuredClone(edit)]}}));setMsg(result.ok?'样式已保存，可与任意主题搭配。':result.error);if(result.ok){setView(edit);setEdit(null)}}
  const saveTheme=()=>{if(!themeEdit||!themeEdit.name.trim()||!validTemplate(applyTheme(templates[0],themeEdit))){setMsg('请填写主题名称，并使用有效的十六进制颜色值。');return}const result=mt.command('保存报告主题',b=>({...b,reporting:{...reporting(b),themes:[...(reporting(b).themes??[]).filter(t=>t.id!==themeEdit.id),structuredClone(themeEdit)]}}));setMsg(result.ok?'主题已保存，班级和个人样式均可复用。':result.error);if(result.ok){setTheme(themeEdit);setThemeEdit(null)}}
  return <div className="flex flex-col gap-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">模板中心</h2><p className="text-sm text-muted-foreground">样式决定排布，主题决定配色。点击卡片即时预览。</p></div><label className="text-sm">报告类型<select aria-label="模板类型" className={inputCls} value={kind} onChange={e=>{setKind(e.target.value as ReportKind);setView(null);setEdit(null);setObject(0)}}><option value="class">班级报告</option><option value="personal">个人报告</option></select></label></div>
    <div className="grid items-start gap-3 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
      <aside className="flex min-w-0 flex-col gap-2 lg:max-h-[calc(100dvh-160px)] lg:overflow-y-auto"><div className="flex gap-2" role="group" aria-label="配置分类"><Btn size="sm" variant={tab==='style'?'primary':'outline'} onClick={()=>setTab('style')}>样式 · 布局</Btn><Btn size="sm" variant={tab==='theme'?'primary':'outline'} onClick={()=>setTab('theme')}>主题 · 配色</Btn></div>
        <p className="text-sm text-muted-foreground">{tab==='style'?'仅切换元素排布，不改变已选配色。':'仅切换配色，不改变已选布局。'}</p>
        <div className="grid grid-cols-2 gap-2">{tab==='style'?templates.map(t=><button key={t.id} type="button" aria-pressed={layout?.id===t.id} onClick={()=>choose(t)} className={`rounded-md border px-3 py-2 text-left transition-colors focus-visible:outline-2 focus-visible:outline-primary ${layout?.id===t.id?'border-primary bg-accent text-accent-foreground':'border-border bg-card text-card-foreground hover:bg-accent'}`}><span className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">{t.name}</span><span className="text-sm text-muted-foreground">{t.owner?'自定义':'系统'}{t.id===defaultId?' · 默认':''}</span></span><span className="text-sm text-muted-foreground">{descriptions[t.preset??t.id]??'自定义报告结构'}</span></button>):themes.map(t=><button key={t.id} type="button" aria-pressed={!themeEdit&&theme.id===t.id} onClick={()=>{setTheme(t);setThemeEdit(null);if(!layout)choose(templates[0])}} className={`flex items-center justify-between gap-2 rounded-md border px-3 py-3 text-left focus-visible:outline-2 focus-visible:outline-primary ${!themeEdit&&theme.id===t.id?'border-primary bg-accent text-accent-foreground':'border-border bg-card text-card-foreground hover:bg-accent'}`}><span className="text-sm font-semibold">{t.name}</span><span className="flex gap-1" aria-hidden="true">{[t.color,t.headerBackground,t.borderColor,t.background].map((color,i)=><span key={i} className="size-5 rounded border border-border" style={{backgroundColor:color}}/>)}</span></button>)}</div>
        {tab==='style'&&layout?<div className="flex flex-wrap gap-2"><Btn size="sm" onClick={()=>copy(layout)}>复制为我的样式</Btn><Btn size="sm" disabled={!!edit||layout.id===defaultId} onClick={setDefault}>{layout.id===defaultId?'当前默认样式':'设为默认样式'}</Btn>{layout.owner===teacherId?<><Btn size="sm" onClick={()=>setEdit(structuredClone(layout))}>编辑样式</Btn><Btn size="sm" disabled={!!edit||!state.templates.some(t=>t.id===layout.id)} onClick={()=>{const result=mt.command('归档报告样式',b=>({...b,reporting:{...reporting(b),templates:reporting(b).templates.map(t=>t.id===layout.id?{...t,archived:true}:t)}}));setMsg(result.ok?'样式已停用，不再出现在可选列表中；已有发布准备和历史报告不变。':result.error);if(result.ok){setView(null);setEdit(null)}}}>停用样式（归档）</Btn></>:null}</div>:null}
        {tab==='style'&&layout?.owner===teacherId?<p className="text-sm text-muted-foreground">停用（归档）仅隐藏已保存的样式，不删除历史报告；编辑中的样式请先保存或取消编辑。</p>:null}
        {tab==='theme'?<div className="flex flex-wrap gap-2"><Btn size="sm" onClick={()=>{setThemeEdit({...theme,id:crypto.randomUUID(),owner:teacherId,name:`${theme.name} · 我的主题`});if(!layout)choose(templates[0])}}>复制为我的主题</Btn>{theme.owner===teacherId?<Btn size="sm" onClick={()=>{setThemeEdit(structuredClone(theme));if(!layout)choose(templates[0])}}>编辑主题</Btn>:null}</div>:null}
        {tab==='style'&&edit?<div className="flex flex-col gap-3"><label className="text-sm">样式名称<input className={inputCls} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><ReportOptionsEditor currentReport={samples[index]} value={edit} onChange={setEdit} includeTheme={false}/><div className="flex gap-2"><Btn onClick={save}>保存样式</Btn><Btn onClick={()=>{setView(templates.find(t=>t.id===edit.id)??templates[0]);setEdit(null)}}>取消编辑</Btn></div></div>:null}
        {tab==='theme'&&themeEdit&&active?<div className="flex flex-col gap-3"><label className="text-sm">主题名称<input className={inputCls} value={themeEdit.name} onChange={e=>setThemeEdit({...themeEdit,name:e.target.value})}/></label><ReportThemeEditor value={active} onChange={t=>setThemeEdit({...themeEdit,...themeOf(t),id:themeEdit.id,owner:teacherId,name:themeEdit.name})}/><div className="flex gap-2"><Btn onClick={saveTheme}>保存主题</Btn><Btn onClick={()=>setThemeEdit(null)}>取消编辑</Btn></div></div>:null}
      </aside>
      {active?<section className="flex min-w-0 flex-col gap-2 rounded-lg border border-border bg-card p-3 text-card-foreground lg:sticky lg:top-20"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-semibold">{layout?.name}</h3><p className="text-sm text-muted-foreground">配色：{(themeEdit??theme).name}</p></div><div className="flex gap-2"><Btn size="sm" variant="primary" disabled={!!edit||!!themeEdit||!validTemplate(active)} onClick={()=>onApply(active)}>应用样式与主题</Btn><Btn size="sm" onClick={()=>{setView(null);setEdit(null);setThemeEdit(null)}}>关闭预览</Btn></div></div>
        {active&&!validTemplate(active)?<p role="status" className="text-sm text-destructive">当前颜色格式或样式配置无效，预览暂时保留上一次有效配置。颜色请使用 #RGB 或 #RRGGBB 格式。</p>:null}
        {active&&templateContrastWarnings(active).length?<p role="status" className="text-sm text-muted-foreground">可读性建议：{templateContrastWarnings(active).join('、')}对比度偏低，可调整文字或背景颜色；不影响预览、保存和应用。</p>:null}
        {samples.length?<><div className="flex flex-wrap items-center gap-2"><Btn size="sm" disabled={index===0} onClick={()=>setObject(index-1)}>上一个对象</Btn><select aria-label="模板预览对象" className="min-w-0 flex-1 rounded border border-input p-2 text-sm" value={index} onChange={e=>setObject(Number(e.target.value))}>{samples.map((r,i)=><option key={r.key} value={i}>{r.name} · {r.kind==='personal'?'个人':r.audience==='internal'?'校内核对':'班级家长版'}</option>)}</select><Btn size="sm" disabled={index===samples.length-1} onClick={()=>setObject(index+1)}>下一个对象</Btn></div><ReportView report={samples[index]} adaptive/></>:<p role="status" className="min-h-64 text-sm">正在准备预览；若未显示���请检查颜色格式或切换有记录的教学周。</p>}
      </section>:<div className="flex min-h-64 items-center justify-center rounded-lg border border-dashed border-border text-sm text-muted-foreground">选择左侧样式或主题，查看实际报告</div>}
    </div>{msg?<p role="status" className="text-sm">{msg}</p>:null}
  </div>
}
